language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

script: ./gradlew testDevDebugUnitTest -i

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  slack: tba-android:g0OFNqSnj71KnQC8IHGXnzhj
  email: false
