language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.1
    - android-21
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
  
script: ./gradlew test --info

notifications:
  slack: tba-android:g0OFNqSnj71KnQC8IHGXnzhj
  email: false
